### ISSUE TITLE
import requests error

### ISSUE THREAD

**Issue by kidsyn** [frappe/biometric-attendance-sync-tool#10]
Traceback (most recent call last):
  File "push_to_erpnext.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

what is the solution to fix this?

**Comment by promise4all** [comment]
Are you running the code on the same machine where ERPNEXT is installed?

**Comment by kidsyn** [comment]
> Are you running the code on the same machine where ERPNEXT is installed?
> You're obviously don't have the 'requests' module in your python PATH.
> Setup dependencies as described in the instructions, using cd push-biometric-erpnext && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt

Thanks its fixed

**Comment by kidsyn** [comment]
> Are you running the code on the same machine where ERPNEXT is installed?
> You're obviously don't have the 'requests' module in your python PATH.
> Setup dependencies as described in the instructions, using cd push-biometric-erpnext && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt

i am running the code on the same machine where ERPNEXT is installed

**Comment by f-9t9it** [comment]
This is a permission error. 
I can run the same with `sudo` also `PyQt5` fails to install without sudo from the requirements file.

**Comment by gavindsouza** [comment]
@f-9t9it you can't install it using the `--user` flag for your current user either?
