### ISSUE TITLE
No Employee found for the given employee field value

### ISSUE THREAD

**Issue by muslimbi** [frappe/biometric-attendance-sync-tool#18]
"_server_messages": "["{\"message\": \"No Employee found for the given employee field value. 'attendance_device_id': HR-ERP-109\", \"indicator\": \"red\", \"raise_exception\": 1}"]"

**Comment by karthikeyan5** [comment]
@muslimbi, the solution to this error is already [available over at the forum](https://discuss.erpnext.com/t/how-to-integrate-biometric-device-in-erp-next-attendance/52252/18?u=karthikeyan5). 

Request you to do a search before you create an issue here. Also, please give more description and background when creating issues.

Regards,
Karthi
