### ISSUE TITLE
Version-13 Frappe.cloud : Fingerprint machine syncing issue.

### ISSUE THREAD

**Issue by sammish** [frappe/biometric-attendance-sync-tool#20]
Hello, Team

Finger Print machine become hang when we run crontab in Linux biometric-attendance-sync-tool.

![WhatsApp Image 2020-11-19 at 4 22 59 PM](https://user-images.githubusercontent.com/12432802/102453024-7932da00-404c-11eb-8a92-ee5246f7a8d3.jpeg)

**Comment by sammish** [comment]
@karthikeyan5 @KaviyaPeriyasamy 

Please consider this issue.

**Comment by karthikeyan5** [comment]
@sammish, in case you are still facing this.

here is what you could do to provide more information on this:
- Follow the steps below to run the device test and provide the output here:
  - Clone the [pyzk repo](https://github.com/fananimi/pyzk)
  - navigate to the pyzk directory
  - run this in your terminal/cmd tool `./test_machine.py -a 192.168.1.201 -p 4370 -b` (change the device IP address and port as per your device)

**Comment by sammish** [comment]
@karthikeyan5 

Thanks. Let me check.
