### ISSUE TITLE
Remove duplicated timestamp for employee

### ISSUE THREAD

**Issue by 3b0000d** [frappe/biometric-attendance-sync-tool#26]
I have error says:
frappe.exceptions.ValidationError: This employee already has a log with the same timestamp.<Br><a href="#Form/Employee Checkin/EMP-CKIN-05-2021-000166" style="font-weight: bold;">Employee Checkin EMP-CKIN-05-2021-000166</a>
and the status of this employee status : '2'
I tried to delete record that contain this problem from file floor_7_192_168_1_2_last_fetch_dump.json but the problem still exist.|
Any kind of help please?

**Comment by amontaser** [comment]
I’m dealing with the same problem. any help
