### ISSUE TITLE
Not Working on Version 14

### ISSUE THREAD

**Issue by niyazrazak** [frappe/biometric-attendance-sync-tool#32]

**Comment by karthikeyan5** [comment]
Please share additional information on steps you followed or errors you are seeing.

**Comment by niyazrazak** [comment]
In version 13  
url = config.ERPNEXT_URL + "/api/method/erpnext.hr.doctype.employee_checkin.employee_checkin.add_log_based_on_employee_field"

in version 14:
 url = config.ERPNEXT_URL + "/api/method/hrms.hr.doctype.employee_checkin.employee_checkin.add_log_based_on_employee_field"

Module has been change

**Comment by niyazrazak** [comment]
@karthikeyan5 hope your understand

**Comment by karthikeyan5** [comment]
@niyazrazak, got it... Looks like there needs to be an option to select the version (or URL) in the config file. I will push the changes soon...

**Comment by cha254** [comment]
I want to fetch employee attendance from a specific date period.
i.e The attendance machine have attendance log from 01-Jan-2020 to current date of 2022. I just want to fetch log from 01-Jan-2022 to current date of 2022.
I have edited local_config file of biometric attendance sync tool where I added my required date in “IMPORT_START_DATE = 20220101” as given format but can’t get result as expected.
Any help in this regard will be highly appreciated. 
Thanks in advance.

**Comment by karthikeyan5** [comment]
@niyazrazak, @alviriseup this issue has been resolved in PR #35.

You now have to add the following key to the `local_config.py` file to make this script work for v14
```python 
ERPNEXT_VERSION = 14
```

**Comment by karthikeyan5** [comment]
> I want to fetch employee attendance from a specific date period. i.e The attendance machine have attendance log from 01-Jan-2020 to current date of 2022. I just want to fetch log from 01-Jan-2022 to current date of 2022. I have edited local_config file of biometric attendance sync tool where I added my required date in “IMPORT_START_DATE = 20220101” as given format but can’t get result as expected. Any help in this regard will be highly appreciated. Thanks in advance.

@cha254, please provide more details on what you have followed and the issues you are facing on https://discuss.erpnext.com

This thread is not the right place for this.

**Comment by cha254** [comment]
Thanks @karthikeyan5
