### ISSUE TITLE
Error in pushing biometric device data to ERPNext

### ISSUE THREAD

**Issue by alviriseup** [frappe/biometric-attendance-sync-tool#33]
Hello Team,

I am trying to use the biometric attendance sync tool to take auto attendance for my local ERPNext instance. I am able to fetch the data from my ZKTeco device; however, I am unable to push the data into ERPNext.

The error log shows a ModuleNotFoundError. I have run `bench setup requirements` to make sure that I have the correct modules, but the problem still persists. I have gone through almost all the relevant topics in the forum, but unfortunately, could not find a solution.

I am attaching my error log and logs log for a better understanding. Please note that I'm using version 14, OS Ubuntu 22.04 LTS.

What am I missing here? TIA

Error Log: [error.log](https://github.com/frappe/biometric-attendance-sync-tool/files/9851487/error.log)

Logs log: [logs.log](https://github.com/frappe/biometric-attendance-sync-tool/files/9851491/logs.log)

**Comment by karthikeyan5** [comment]
@alviriseup, what is your version of ERPNext?

**Comment by alviriseup** [comment]
@karthikeyan5 I'm using ERPNext version 14.

![Screenshot from 2022-10-27 15-16-42](https://user-images.githubusercontent.com/95750048/198245095-a704f2d9-bf0a-454b-b071-3c10fd776afe.png)

**Comment by karthikeyan5** [comment]
@alviriseup, this is a known issue tracked in #32.
Closing this for now. 

Thanks for reporting with a complete error log and everything.
