### ISSUE TITLE
Can't clear the cache memory of the logs directory of biometric attendance sync tool.

### ISSUE THREAD

**Issue by ArunaDevraj** [frappe/biometric-attendance-sync-tool#36]
### Information about bug

When running the erpnext_sync.py script, the data is fetched every time from the import start date.
This causes the cache memory of the logs directory is getting filled.
Instead of this, what we have to do in the erpnext_sync.py script to fetch only that days data?
And after fetching the data, we have to clear the cache memory automatically.

### Module

HR

### Version

ERPNext: v13.35.3 (version-13)

Frappe Framework: v13.35.2 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
logs directory of biometric-attendance-sync-tool-1.0 is getting filled.
```

**Comment by karthikeyan5** [comment]
@ArunaDevraj, what exactly do you mean by "logs directory is getting filled". What is the exact size of you logs directory? What is the error message or issue you are facing? Please provide more information.

**Comment by ArunaDevraj** [comment]
Cache memory of logs directory are fulled. Almost after 4000

**Comment by ArunaDevraj** [comment]
Cache memory of logs directory are fulled. Almost after 4000 employee checkin details are fetched, erpnext_sync.py script is still running, but data is not getting in the logs

**Comment by karthikeyan5** [comment]
> logs directory are fulled.

@ArunaDevraj, saying the logs directory is full does not make sense to me. please define what you mean by "fulled". Are you running out of disk space? what exactly is the size of your logs directory in MB(megabyte)?


> erpnext_sync.py script is still running, but data is not getting in the logs

This script is designed to run perpetually. So, after completing a single import the script does not exit. If your data does not get imported, it could mean that there is some error while importing your logs. please check your `error.log` and `logs.log` for more details.

**Comment by karthikeyan5** [comment]
Also, please start a discussion on https://discuss.erpnext.com with more logs and details to further get help with your issue.
