### ISSUE TITLE
Hi, Issue regarding automatic attendance.

### ISSUE THREAD

**Issue by ArunaDevraj** [frappe/biometric-attendance-sync-tool#40]
In some attendance , it shows working hours, checkin & check out time of the employee if he/she is present. But in some attendance it doesnt shows nothing the above mentioned, only shows the shift type and present. Actually this may not be an issue. please share me the idea of why this occurs. 
/home/aruna/Downloads/IMG-20221121-WA0003.jpg
/home/aruna/Downloads/IMG-20221121-WA0005.jpg

**Comment by ArunaDevraj** [comment]
Also how half day is worked in auto attendance

**Comment by karthikeyan5** [comment]
@ArunaDevraj, your screenshots are not visible. 

Also, please use https://discuss.erpnext.com to get help on your implementation issues.
