### ISSUE TITLE
No such file or directory  when try to bench get-app biometric-attendance-sync-tool

### ISSUE THREAD

**Issue by lohnxongmixay** [frappe/biometric-attendance-sync-tool#41]
FileNotFoundError: [Errno 2] No such file or directory: '/opt/erp/apps/biometric-attendance-sync-tool/setup.py'

I checked, and there is no setup.py

If Is there the same file listed as install.py?

**Comment by karthikeyan5** [comment]
@lohnxongmixay, this is not an application for the frappe framework. 

This is a python script meant to be installed on a computer in the local network where the biometric device is present.

Please read this https://docs.erpnext.com/docs/v13/user/manual/en/setting-up/articles/integrating-erpnext-with-biometric-attendance-devices

Then, Please read the readme of this repository.

**Comment by lohnxongmixay** [comment]
Thank you so much,

And, so sorry for my bad
