### ISSUE TITLE
Error after Starting Service

### ISSUE THREAD

**Issue by Mohd200** [frappe/biometric-attendance-sync-tool#43]
Good day All

I'm facing an issue When booting up the python files "attendance-sync.py" to start the connection between the ZKTeco device and the ERPNext, it won't start the connection due to an error in the "json.decoder" file in the Python App inside the Middle-Man PC
![4YnAdwY](https://user-images.githubusercontent.com/32062135/213382992-6bef8d62-c86b-4aa2-9655-a220878b9f45.png)

I keep facing "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)" error every time I try to start the service.
P.S: I don't have the ZKTeco software as I never needed to, also, both the ZKTeco and the PC are online and in the same network and pinging correctly.
before this error happened, the connection was working perfectly as I followed the instructions in Biometric Attendance Sync Tool (For ERPNext) GitHub page, and it was fetching the data accordingly and correctly and without any delay.

Please help me find a solution to my problem
Let me know if you need more info regarding the issue

**Comment by Mohd200** [comment]
@karthikeyan5 @gavindsouza @Anurag810 @KaviyaPeriyasamy @surajshetty3416 @rtdany10 

Could you please advise on this issue?

**Comment by rtdany10** [comment]
There is a `status.json` file in your logs directory, delete it and try.

**Comment by Mohd200** [comment]
Hello All

@rtdany10 your solution worked, thank you for that, however, the problem doesn't end there.
I can't establish the connections anymore between the ERPNext and the ZKTeco device due to an error message (API Call to ERPNext Failed.)
I have generated the API from User Accounts multiple times, even created new Users (With HR Manager Role) to Generate a brand new API Key and API Secret, the Middle-Man PC is in the Same network as the ZKTeco device and pinging succesfully and both online.
I viewed the "error.txt" file and the last line was the error message: Exception: API Call to ERPNext Failed.
![image](https://user-images.githubusercontent.com/32062135/215964673-9ab6c076-4587-4dbc-a49c-5212b16672c8.png)

Then I noticed a message appearing in the Python CMD 
![image](https://user-images.githubusercontent.com/32062135/215964794-e41bf071-8a81-4899-9502-3960e1f3fa33.png)


I'm at a loss here, can you please help me...
@karthikeyan5 @gavindsouza @Anurag810 @KaviyaPeriyasamy @surajshetty3416 @rtdany10

**Important Note: Now we're using the Version 14 of ERPNext**
![image](https://user-images.githubusercontent.com/32062135/215965097-d45984d1-3330-429e-a2b3-e10f89dddc9e.png)

Therefore, I had to change something in the "erpnext_sync.py" file:
![image](https://user-images.githubusercontent.com/32062135/215965379-cfcaf592-87c9-4052-bd76-095e72185ce0.png)

**I updated Line 170 from:**
url = config.ERPNEXT_URL + "/api/method/erpnext.hr.doctype.employee_checkin.employee_checkin.add_log_based_on_employee_field"

**To**:
url = config.ERPNEXT_URL + "/api/method/hrms.hr.doctype.employee_checkin.employee_checkin.add_log_based_on_employee_field"

**Comment by rtdany10** [comment]
@Mohd200 seems like some issue with the name of Shift Type in your ERPNext. Is it in English? Is valid shift assigned for/set in employee?

**Comment by Mohd200** [comment]
@rtdany10 
I would like to thank you for helping notice that the "Default Shift" docfield was missing in the Employee Master, I had to add it via Customization and once done the docfield was already filled by the Default Shift for each Employee.

However, **unfortunately this did not solve my issue**, I am still receiving the same error message.
the Python CMD is no longer displaying any error messages only the "error.txt" in Logs folder.

[python files.zip](https://github.com/frappe/biometric-attendance-sync-tool/files/10554523/python.files.zip)
Here are my python files, hopefully they will help...

**Comment by rtdany10** [comment]
> @rtdany10 I would like to thank you for helping notice that the "Default Shift" docfield was missing in the Employee Master, I had to add it via Customization and once done the docfield was already filled by the Default Shift for each Employee.

Can you share the screenshot of the shift type?

**Comment by Mohd200** [comment]
Here is the Shift Type
![image](https://user-images.githubusercontent.com/32062135/216038731-e6b35bf3-7056-4481-b5de-c678e480ad1e.png)

![image](https://user-images.githubusercontent.com/32062135/216038872-bcc79e23-b10c-48c9-a020-351f6aab275f.png)

Hopefully these images will help

**Comment by rtdany10** [comment]
> only the "error.txt" in Logs folder.

Also share the content of this file.

**Comment by rtdany10** [comment]
> `frappe.exceptions.PermissionError`

Make sure the API user has access to create Employee Checkin

**Comment by Mohd200** [comment]
All Users who generated API from already have HR Manager Role

**Comment by Mohd200** [comment]
I tried to connect on another PC and it connected perfectly and it was working well
Until Yesterday where suddenly stopped and started the Error messages

Now both PCs are not working...
Please help me

**Comment by rtdany10** [comment]
> All Users who generated API from already have HR Manager Role

I'm not talking about Role. Maybe that role doesn't have access to create?
Login to ERP as the API user and manually create a checkin to see if there are any issues.

**Comment by Mohd200** [comment]
Done with no issues, the User has "System Manager" Role as well...

**Comment by Mohd200** [comment]
I just tried to "Start Service" and this is the last message in the Error file:

2023-02-01 17:03:54,184	ERROR	exception when calling pull_process_and_push_data function for device{"device_id": "1", "ip": "10.51.114.143", "punch_direction": "AUTO", "clear_from_device_on_fetch": ""}
Traceback (most recent call last):
  File "C:\Users\mhmd-\OneDrive\Desktop\Output\Bio-metric sync tool\biometric-attendance-sync-tool-v1.0-win32\erpnext_sync.py", line 51, in main
    pull_process_and_push_data(device, device_attendance_logs)
  File "C:\Users\mhmd-\OneDrive\Desktop\Output\Bio-metric sync tool\biometric-attendance-sync-tool-v1.0-win32\erpnext_sync.py", line 129, in pull_process_and_push_data
    raise Exception('API Call to ERPNext Failed.')
Exception: API Call to ERPNext Failed.

**Comment by Mohd200** [comment]
@karthikeyan5 @gavindsouza @Anurag810 @KaviyaPeriyasamy @surajshetty3416 @rtdany10

I would appreciate your guidance on this issue...
Thank you

**Comment by Mohd200** [comment]
OK I switched to another User with Different Brand-new API and it's working Perfectly just like before.

Thank you all for your help, especially @rtdany10

**Comment by Mohd200** [comment]
OK I switched to another User with Different Brand-new API and it's working Perfectly just like before.

Thank you all for your help, especially @rtdany10
