### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mn9t21xp/PyQt5/

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/biometric-attendance-sync-tool#9]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mn9t21xp/PyQt5/

**Comment by flexy2ky** [comment]
Full traceback on this issue:

> flexy@biometrics:~/push-biometric-erpnext$ cd push-biometric-erpnext && sudo pip3 install -r requirements.txt
> -bash: cd: push-biometric-erpnext: No such file or directory
> flexy@biometrics:~/push-biometric-erpnext$ cd
> flexy@biometrics:~$ cd push-biometric-erpnext && sudo pip3 install -r requirements.txt
> The directory '/home/flexy/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/home/flexy/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1))
> Collecting pickledb (from -r requirements.txt (line 2))
>   Downloading https://files.pythonhosted.org/packages/29/7f/ae7a32f125c6165941ed5c547bff7e6fbd385658fc6e490c2ee73c78c4c2/pickleDB-0.9.2.tar.gz
> Collecting pyzk (from -r requirements.txt (line 3))
>   Downloading https://files.pythonhosted.org/packages/59/83/a60af4e83c492c7dceceeabd677aa87bbaf2d8910b3d1b973295e560f421/pyzk-0.9.tar.gz
> Collecting PyQt5 (from -r requirements.txt (line 4))
>   Downloading https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz (3.2MB)
>     100% |████████████████████████████████| 3.2MB 314kB/s
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/usr/lib/python3.6/tokenize.py", line 452, in open
>         buffer = _builtin_open(filename, 'rb')
>     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-9r2ay_m0/PyQt5/setup.py'
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9r2ay_m0/PyQt5/
>

**Comment by f-9t9it** [comment]
Need to run with `sudo`
